import type { Metadata } from "next";
import "./globals.css";

import { Exo } from 'next/font/google'

const exo = Exo({
  weight: ['100','200','300','400','500','600','700','800','900'],

});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${exo.className} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
